# Generated by Django 5.0.1 on 2024-01-19 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("sku", models.CharField(max_length=100)),
                ("planta", models.CharField(max_length=100)),
                ("nombre", models.CharField(max_length=100)),
                ("nombre_abreviado", models.CharField(max_length=100)),
                ("ean", models.CharField(max_length=100)),
                ("destino", models.CharField(max_length=100)),
                ("version_etiqueta", models.CharField(max_length=100)),
                ("nb_primaria", models.CharField(max_length=100)),
                ("dias_caducidad", models.IntegerField()),
                ("familia_path", models.CharField(max_length=100)),
                ("descripcion_linea_1", models.TextField()),
                ("descripcion_linea_2", models.TextField()),
                ("descripcion_linea_3", models.TextField()),
                ("proteina", models.FloatField()),
                ("humedad", models.FloatField()),
                ("ceniza", models.FloatField()),
                ("grasa", models.FloatField()),
                ("fibra", models.FloatField()),
                ("ingredientes_linea_1", models.TextField()),
                ("ingredientes_linea_2", models.TextField()),
                ("ingredientes_linea_3", models.TextField()),
                ("ingredientes_linea_4", models.TextField()),
                ("ingredientes_linea_5", models.TextField()),
                ("registro_sanitario", models.CharField(max_length=100)),
                ("fabricado_para", models.CharField(max_length=100)),
                ("direccion_fabricante", models.CharField(max_length=100)),
                ("ruc_fabricante", models.CharField(max_length=100)),
                ("fecha_creacion", models.DateTimeField()),
                ("is_actualizado", models.BooleanField()),
                ("fecha_actualizacion", models.DateTimeField()),
                ("is_new", models.BooleanField()),
            ],
        ),
    ]
