# Generated by Django 5.0.1 on 2024-04-14 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenproduccion",
            name="nb_primaria",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nb_primaria",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
