# Generated by Django 5.0.1 on 2024-02-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_producto_descripcion_linea_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrdenProduccion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sku", models.CharField(max_length=20)),
                ("planta_primaria", models.CharField(max_length=10)),
                ("nombre_producto", models.CharField(max_length=50)),
                ("nombre_abreviado", models.CharField(max_length=20)),
                ("ean", models.CharField(max_length=15)),
                ("destino_primaria", models.CharField(default="EC", max_length=10)),
                ("version_primaria", models.CharField(max_length=10)),
                ("nb_primaria", models.CharField(max_length=5)),
                ("dias_caducidad", models.IntegerField()),
                ("id_path", models.CharField(max_length=30)),
                ("familia_path", models.CharField(max_length=30)),
                ("familia_path_colos", models.CharField(max_length=100)),
                ("descripcion_linea_1", models.TextField(blank=True, null=True)),
                ("descripcion_linea_2", models.TextField(blank=True, null=True)),
                ("descripcion_linea_3", models.TextField(blank=True, null=True)),
                ("proteina", models.FloatField()),
                ("humedad", models.FloatField()),
                ("ceniza", models.FloatField()),
                ("grasa", models.FloatField()),
                ("fibra", models.FloatField()),
                ("ingredientes_linea_1", models.TextField(blank=True, null=True)),
                ("ingredientes_linea_2", models.TextField(blank=True, null=True)),
                ("ingredientes_linea_3", models.TextField(blank=True, null=True)),
                ("ingredientes_linea_4", models.TextField(blank=True, null=True)),
                ("ingredientes_linea_5", models.TextField(blank=True, null=True)),
                ("registro_sanitario", models.CharField(max_length=20)),
                ("fabricado_para", models.CharField(max_length=100)),
                ("direccion_fabricante", models.CharField(max_length=100)),
                ("ruc_fabricante", models.CharField(max_length=100)),
                (
                    "version_secundaria",
                    models.CharField(blank=True, max_length=5, null=True),
                ),
                (
                    "cantidad_terciaria",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "peso_neto_terciaria",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("fecha_creacion", models.DateTimeField()),
                ("estado", models.CharField(max_length=10)),
                ("fecha_final", models.DateTimeField()),
                ("planta", models.IntegerField()),
                ("prensa", models.CharField(blank=True, max_length=2, null=True)),
                ("prensa_numero", models.IntegerField(blank=True, null=True)),
                ("linea", models.CharField(max_length=50)),
                ("lote_completo", models.BooleanField(default=False)),
                (
                    "lote_numeros",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("turno", models.CharField(max_length=20)),
            ],
        ),
    ]
