# Generated by Django 5.0.1 on 2024-05-18 22:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_ordenproduccion_nb_primaria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="palet",
            name="fechas_movimientos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="palet",
            name="movimientos_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(), blank=True, default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="palet",
            name="movimientos_nombre",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="palet",
            name="peso_neto_terciaria",
            field=models.CharField(default="1650 KG", max_length=10),
        ),
        migrations.AddField(
            model_name="palet",
            name="usuarios_movimientos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="nombre_abreviado",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="registro_sanitario",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre_abreviado",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="producto",
            name="registro_sanitario",
            field=models.CharField(max_length=30),
        ),
    ]
