# Generated by Django 5.0.1 on 2024-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_palet_fechas_movimientos_palet_movimientos_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="inicio_contador_string",
            field=models.CharField(default="0001", max_length=10),
        ),
        migrations.AddField(
            model_name="palet",
            name="linea_letra",
            field=models.CharField(default="3B", max_length=10),
        ),
        migrations.AddField(
            model_name="palet",
            name="numero_palet_string",
            field=models.CharField(default="0001", max_length=10),
        ),
    ]
