# Generated by Django 5.0.1 on 2024-02-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_ordenproduccion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenproduccion",
            name="lote_completo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="lote_numeros",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="turno",
            field=models.IntegerField(),
        ),
    ]
