# Generated by Django 5.0.1 on 2024-07-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_ordenproduccion_inicio_contador_string_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenproduccion",
            name="nb_primaria",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nb_primaria",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre_producto",
            field=models.CharField(max_length=100),
        ),
    ]
