# Generated by Django 5.0.1 on 2024-02-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_ordenproduccion_inicio_contador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="inicio_contador_general",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
