# Generated by Django 5.0.1 on 2024-12-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_ordenproduccion_nb_primaria_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Turno",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("linea", models.CharField(max_length=5)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_final", models.DateTimeField()),
                (
                    "fecha_dia_creacion_string",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("estado", models.CharField(max_length=10)),
                ("turno", models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="fecha_continuar",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="palet",
            name="subido_a_firebase",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="palet",
            name="subido_a_vitacontrol",
            field=models.BooleanField(default=False),
        ),
    ]
