# Generated by Django 5.0.1 on 2024-12-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_turno_ordenproduccion_fecha_continuar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="subido_a_vitacontrol",
            field=models.BooleanField(default=False),
        ),
    ]
