# Generated by Django 5.0.1 on 2024-03-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_ordenproduccion_inicio_contador_general"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="id_fb_producto",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="id_producto",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
