# Generated by Django 5.0.1 on 2024-12-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_ordenproduccion_subido_a_vitacontrol"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="actualizado_a_firebase",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="actualizado_a_vitacontrol",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="id_vitacontrol",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="libre",
            field=models.BooleanField(default=False),
        ),
    ]
