# Generated by Django 5.0.1 on 2024-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_ordenproduccion_id_fb_producto_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="fin_contador",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ordenproduccion",
            name="fin_contador_general",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
