# Generated by Django 5.0.1 on 2024-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_ordenproduccion_fin_contador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="fecha_caducidad_string",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
