# Generated by Django 5.0.1 on 2024-12-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_ordenproduccion_actualizado_a_firebase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="palet",
            name="id_vitacontrol",
            field=models.CharField(default="", max_length=15),
        ),
        migrations.AddField(
            model_name="producto",
            name="id_vitacontrol",
            field=models.CharField(default="", max_length=15),
        ),
    ]
