# Generated by Django 5.0.1 on 2024-03-27 09:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_ordenproduccion_fecha_caducidad_string"),
    ]

    operations = [
        migrations.CreateModel(
            name="Palet",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_fb", models.CharField(max_length=50)),
                ("sku", models.CharField(max_length=25)),
                ("nombre_producto", models.CharField(max_length=100)),
                ("ean13", models.CharField(max_length=30)),
                ("planta_primaria", models.CharField(max_length=10)),
                ("linea", models.CharField(max_length=5)),
                ("llenadora", models.CharField(max_length=5)),
                ("prensa", models.CharField(max_length=5)),
                ("prensa_numero", models.IntegerField()),
                ("version_primaria", models.IntegerField()),
                ("lote_completo", models.CharField(max_length=30)),
                ("cantidad", models.IntegerField()),
                ("sscc", models.CharField(max_length=25, unique=True)),
                ("fecha_elaboracion", models.DateField()),
                ("fecha_caducidad", models.DateField()),
                ("numero_palet", models.IntegerField()),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("id_bodega_origen", models.IntegerField()),
                ("id_bodega_destino", models.IntegerField()),
                (
                    "movimientos_id",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "movimientos_nombre",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "fechas_movimientos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DateField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "usuarios_movimientos",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("turno", models.IntegerField()),
                ("id_usuario", models.CharField(max_length=50)),
                ("id_orden_produccion", models.IntegerField()),
                ("subido_a_firebase", models.BooleanField()),
                ("subido_a_vitacontrol", models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="linea",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="nombre_producto",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="prensa",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
