# Generated by Django 5.0.1 on 2024-12-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_palet_id_vitacontrol_producto_id_vitacontrol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenproduccion",
            name="id_vitacontrol",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="palet",
            name="id_vitacontrol",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id_vitacontrol",
            field=models.CharField(blank=True, default="", max_length=15, null=True),
        ),
    ]
