# Generated by Django 5.0.1 on 2024-12-29 05:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_alter_ordenproduccion_id_vitacontrol_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="palet",
            name="codigo_bodega_actual",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AddField(
            model_name="palet",
            name="id_fb_producto",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="palet",
            name="id_producto",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="palet",
            name="id_bodega_destino",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AlterField(
            model_name="palet",
            name="id_bodega_origen",
            field=models.CharField(default="0", max_length=10),
        ),
        migrations.AlterField(
            model_name="palet",
            name="movimientos_id",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(default="0", max_length=10),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
