# Generated by Django 5.0.1 on 2024-03-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_palet_alter_ordenproduccion_linea_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="palet",
            name="fecha_caducidad_string",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
