# Generated by Django 5.0.1 on 2025-02-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_palet_codigo_bodega_actual_palet_id_fb_producto_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenproduccion",
            name="fecha_continuar",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="fecha_final",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fecha_actualizacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fecha_creacion",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
