# Generated by Django 5.0.1 on 2024-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_palet_fecha_caducidad_string"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palet",
            name="ean13",
            field=models.CharField(max_length=100),
        ),
    ]
