# Generated by Django 5.0.1 on 2024-03-28 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_palet_ean13"),
    ]

    operations = [
        migrations.AlterField(
            model_name="palet",
            name="fecha_caducidad",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="palet",
            name="fecha_elaboracion",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="palet",
            name="fechas_movimientos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DateTimeField(), blank=True, default=list, size=None
            ),
        ),
    ]
