# Generated by Django 5.0.1 on 2025-02-06 13:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_alter_ordenproduccion_fecha_continuar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordenproduccion",
            name="fecha_continuar",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="ordenproduccion",
            name="fecha_final",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="palet",
            name="fecha_actualizacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="producto",
            name="fecha_actualizacion",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="turno",
            name="fecha_final",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
