# Generated by Django 5.0.1 on 2024-04-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_palet_fecha_caducidad_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="id_fb",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
