# Generated by Django 5.0.1 on 2024-04-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_ordenproduccion_id_fb"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordenproduccion",
            name="subido_a_firebase",
            field=models.BooleanField(default=False),
        ),
    ]
